# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening this issue. A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md). You can also join [#polaris](https://shopifypartners.slack.com/messages/C8PTBMWNR) on the Shopify Partners Slack.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! A contributor should give feedback soon. If you haven’t already, please check out the [contributing guidelines](https://github.com/Shopify/polaris-react/blob/master/.github/CONTRIBUTING.md). You can also join [#polaris](https://shopifypartners.slack.com/messages/C8PTBMWNR) on the Shopify Partners Slack.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Thanks for your contribution to polaris-react! :tada:

  `/gif congrats`
  ![Congrats!](https://slack-imgs.com/?c=1&url=http%3A%2F%2Friffsy.com%2Fimage%2Fo5rz_tinygif.gif)
