language: node_js
node_js:
  - 5.7.0
before_install:
  - rvm install 2.3.1
  - gem install bundler
  - gem install bundler --version '1.12'
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - script/setup
script:
  - script/check
